### ISSUE TITLE
accessKeyID & accessKeySecret

### ISSUE THREAD

**Issue by sunny0826** [zzxwill/aliyun-ecs-k8s-operator#1]
搞个 Secret 把 accessKeyID 和 accessKeySecret 挂出去呗

**Comment by zzxwill** [comment]
+1 说来惭愧，我还不知道怎么读取 secret。

**Comment by sunny0826** [comment]
以环境变量的形式在 pod 里面读取啊，然后和下面这样将 Secret 注入到环境变量里面：

```yaml
env:
 - name: ADMIN_ACCESS
          valueFrom:
            secretKeyRef:
              key: adminAccess
              name: bot-maoxian-secret
```

或者直接 `client-go` 获取 Secret object 也可以啊
